spring:
  application:
    name: octopus-ai-agent
  profiles:
    active: local
  data:
    redis:
      database: 2
      port: 6379
      host: localhost

  datasource:
    url: jdbc:postgresql://localhost:5432/
    username: postgres
    password: 123456

#  ai:
#    vectorstore:
#      pgvector:
#        index-type: HNSW
#        dimensions: 1536
#        distance-type: COSINE_DISTANCE
#        max-document-batch-size: 10000 # Optional: Maximum number of documents per batch

#  datasource:
#    url: jdbc:mysql://localhost:3306/octopus_ai_agent
#    username: root
#    password: 123456
#    driver-class-name: com.mysql.cj.jdbc.Driver

  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: gemma3:1b
    mcp:
      client:
        sse:
          connections:
            server1: http://localhost:8127
#        stdio:
#          servers-configuration: classpath:mcp-servers.json

logging:
  level:
    com.alibaba.nacos: OFF
    org.springframework.ai: debug

server:
  port: 8123
  servlet:
    context-path: /api

# springdoc-openapi ??????
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.hezhu.octopusaiagent.controller

# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn